name: 'student_placement_analytics'
version: '1.0.0'
config-version: 2

profile: 'student_placement_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  student_placement_analytics:
    bronze:
      +schema: SILVER
      +materialized: view
    silver:
      +schema: SILVER
      +materialized: table
    gold:
      dimensions:
        +schema: GOLD
        +materialized: table
      facts:
        +schema: GOLD
        +materialized: table
      marts:
        +schema: SEM
        +materialized: view
