-- ============================================================
-- PHASE 4: ROLES AND RBAC
-- Run this in Snowflake as ACCOUNTADMIN
-- ============================================================

USE DATABASE PLACEMENT_DB;

-- Switch to security admin or account admin if available for role creation
USE ROLE ACCOUNTADMIN;

-- Create roles
CREATE ROLE IF NOT EXISTS ROLE_ADMIN;
CREATE ROLE IF NOT EXISTS ROLE_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_ETL;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_APP_STREAMLIT;

-- Role hierarchy: ACCOUNTADMIN -> ROLE_ADMIN -> ROLE_ETL -> ROLE_ANALYST
GRANT ROLE ROLE_INGEST        TO ROLE ROLE_ETL;
GRANT ROLE ROLE_ETL           TO ROLE ROLE_ADMIN;
GRANT ROLE ROLE_ANALYST       TO ROLE ROLE_ADMIN;
GRANT ROLE ROLE_APP_STREAMLIT TO ROLE ROLE_ANALYST;
GRANT ROLE ROLE_ADMIN         TO ROLE SYSADMIN;

-- Grant roles to user VASEEM
GRANT ROLE ROLE_ADMIN         TO USER VASEEM;
GRANT ROLE ROLE_ETL           TO USER VASEEM;
GRANT ROLE ROLE_INGEST        TO USER VASEEM;
GRANT ROLE ROLE_ANALYST       TO USER VASEEM;
GRANT ROLE ROLE_APP_STREAMLIT TO USER VASEEM;

-- Warehouse access
GRANT USAGE ON WAREHOUSE PLACEMENT_WH TO ROLE ROLE_INGEST;
GRANT USAGE ON WAREHOUSE PLACEMENT_WH TO ROLE ROLE_ETL;
GRANT USAGE ON WAREHOUSE PLACEMENT_WH TO ROLE ROLE_ANALYST;
GRANT USAGE ON WAREHOUSE PLACEMENT_WH TO ROLE ROLE_APP_STREAMLIT;

-- Database access
GRANT USAGE ON DATABASE PLACEMENT_DB TO ROLE ROLE_INGEST;
GRANT USAGE ON DATABASE PLACEMENT_DB TO ROLE ROLE_ETL;
GRANT USAGE ON DATABASE PLACEMENT_DB TO ROLE ROLE_ANALYST;
GRANT USAGE ON DATABASE PLACEMENT_DB TO ROLE ROLE_APP_STREAMLIT;

-- ROLE_INGEST: only BRONZE + OPS
GRANT ALL PRIVILEGES ON SCHEMA PLACEMENT_DB.BRONZE TO ROLE ROLE_INGEST;
GRANT ALL PRIVILEGES ON SCHEMA PLACEMENT_DB.OPS    TO ROLE ROLE_INGEST;

-- ROLE_ETL: BRONZE read/write + SILVER/GOLD/OPS/SEM write
GRANT ALL PRIVILEGES ON SCHEMA PLACEMENT_DB.BRONZE TO ROLE ROLE_ETL;
GRANT ALL PRIVILEGES ON SCHEMA PLACEMENT_DB.SILVER TO ROLE ROLE_ETL;
GRANT ALL PRIVILEGES ON SCHEMA PLACEMENT_DB.GOLD   TO ROLE ROLE_ETL;
GRANT ALL PRIVILEGES ON SCHEMA PLACEMENT_DB.OPS    TO ROLE ROLE_ETL;
GRANT ALL PRIVILEGES ON SCHEMA PLACEMENT_DB.SEM    TO ROLE ROLE_ETL;

-- ROLE_ANALYST: read SILVER, GOLD, SEM only
GRANT USAGE ON SCHEMA PLACEMENT_DB.SILVER TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA PLACEMENT_DB.GOLD   TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA PLACEMENT_DB.SEM    TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PLACEMENT_DB.SILVER TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PLACEMENT_DB.GOLD   TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA PLACEMENT_DB.SEM    TO ROLE ROLE_ANALYST;

-- ROLE_APP_STREAMLIT: SEM views only
GRANT USAGE  ON SCHEMA PLACEMENT_DB.SEM   TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON ALL VIEWS IN SCHEMA PLACEMENT_DB.SEM TO ROLE ROLE_APP_STREAMLIT;

-- Future grants so new objects are automatically accessible
GRANT SELECT ON FUTURE TABLES IN SCHEMA PLACEMENT_DB.BRONZE TO ROLE ROLE_ETL;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PLACEMENT_DB.SILVER TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PLACEMENT_DB.GOLD   TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PLACEMENT_DB.SEM    TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PLACEMENT_DB.SEM    TO ROLE ROLE_APP_STREAMLIT;
