-- ============================================================
-- PHASE 4: OPS SCHEMA - AUDIT AND REJECTS TABLES
-- Run this in Snowflake as SYSADMIN or ROLE_ETL
-- ============================================================

USE DATABASE PLACEMENT_DB;
USE SCHEMA OPS;

CREATE TABLE IF NOT EXISTS OPS.LOAD_AUDIT (
    AUDIT_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
    BATCH_ID        VARCHAR(50),
    FILE_NAME       VARCHAR(200),
    ENTITY          VARCHAR(50),
    LOAD_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ROW_COUNT       NUMBER,
    STATUS          VARCHAR(20),   -- SUCCESS / FAILURE
    ERROR_MSG       VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS OPS.REJECTS (
    REJECT_ID       NUMBER AUTOINCREMENT PRIMARY KEY,
    BATCH_ID        VARCHAR(50),
    ENTITY          VARCHAR(50),
    SOURCE_ROW      VARIANT,
    REJECT_REASON   VARCHAR(500),
    REJECTED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
