-- ============================================================
-- PHASE 4: SECURITY - MASKING AND ROW-LEVEL SECURITY
-- Run this in Snowflake as ACCOUNTADMIN or SYSADMIN
-- ============================================================

USE DATABASE PLACEMENT_DB;
USE SCHEMA BRONZE;

-- ── Column-level masking: hide student names from non-ETL roles ──────────────

CREATE OR REPLACE MASKING POLICY BRONZE.MASK_NAME AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ROLE_ETL', 'ROLE_ADMIN', 'SYSADMIN') THEN val
        ELSE '***MASKED***'
    END;

CREATE OR REPLACE MASKING POLICY BRONZE.MASK_DOB AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ROLE_ETL', 'ROLE_ADMIN', 'SYSADMIN') THEN val
        ELSE '****-**-**'
    END;

-- ── Row-level security: analysts only see ACTIVE college/company records ─────

USE SCHEMA GOLD;

CREATE OR REPLACE ROW ACCESS POLICY GOLD.RAP_ACTIVE_COLLEGES
AS (status STRING) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ROLE_ADMIN', 'ROLE_ETL', 'SYSADMIN') THEN TRUE
        ELSE status = 'ACTIVE'
    END;

CREATE OR REPLACE ROW ACCESS POLICY GOLD.RAP_ACTIVE_COMPANIES
AS (status STRING) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ROLE_ADMIN', 'ROLE_ETL', 'SYSADMIN', 'ACCOUNTADMIN') THEN TRUE
        ELSE status = 'ACTIVE'
    END;

-- ── Apply Policies ───────────────────────────────────────────────────────────
ALTER TABLE BRONZE.RAW_STUDENTS MODIFY COLUMN FIRST_NAME SET MASKING POLICY BRONZE.MASK_NAME;
ALTER TABLE BRONZE.RAW_STUDENTS MODIFY COLUMN LAST_NAME SET MASKING POLICY BRONZE.MASK_NAME;
ALTER TABLE BRONZE.RAW_STUDENTS MODIFY COLUMN DOB SET MASKING POLICY BRONZE.MASK_DOB;

ALTER TABLE GOLD.DIM_COLLEGE ADD ROW ACCESS POLICY GOLD.RAP_ACTIVE_COLLEGES ON (status);
ALTER TABLE GOLD.DIM_COMPANY ADD ROW ACCESS POLICY GOLD.RAP_ACTIVE_COMPANIES ON (status);

